### ISSUE TITLE
AcquiaDrupalStrict does not sniff install files

### ISSUE THREAD

**Issue by swichers** [acquia/coding-standards-php#1]
Create a `minimal.php` file with the following contents:

```php
<?php

function minimal_example() {

}
```

Run `./vendor/bin/phpcs --standard=AcquiaDrupalStrict minimal.php`

Output:

```
--------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------
 1 | ERROR | [x] Missing file doc comment
 3 | ERROR | [x] Missing function doc comment
--------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------------------------
```

Rename `minimal.php` to `minimal.install`

Run `./vendor/bin/phpcs --standard=AcquiaDrupalStrict minimal.install`

Output: 

No output

Run `./vendor/bin/phpcs --standard=Drupal minimal.install`

Output:

```
------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------
 1 | ERROR | [x] Missing file doc comment
 3 | ERROR | [x] Missing function doc comment
------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------------------
```

I suspect this issue exists for all non-standard PHP_CodeSniffer file extensions, but I only verified install files.

Having `<arg name="extensions" value="inc,install,module,php,profile,test,theme,yml"/>` in my own phpcs.xml.dist file does not alter the behavior. Including `<rule ref="Drupal" />` prior to `<rule ref="AcquiaDrupalStrict" />` does wind up sniffing install files.

**Comment by TravisCarden** [comment]
Thanks for this report, @swichers. I don't immediately perceive the cause of this. I'll look into it as soon as I can.

**Comment by TravisCarden** [comment]
I haven't been able to identify the problem yet. I've reached out for help upstream: https://github.com/squizlabs/PHP_CodeSniffer/issues/2602

**Comment by TravisCarden** [comment]
I've identified the problem. It seems indeed to be a bug in PHP_CodeSniffer. I've worked around it in https://github.com/acquia/coding-standards-php/commit/3ea1e57e1686425e11cb0686a04d12281b1160ef. I plan to commit a few other small changes and cut a new release. Thanks again for reporting this, @swichers!
