### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by danepowell** [acquia/coding-standards-php#14]
There have been a couple of major changes since the last stable release, especially #10 and #13. Can we get a new stable release so downstream projects can take advantage of those fixes?

Edit: I just remembered _I_ can create a new release, since I'm apparently a maintainer :smile:  @TravisCarden you okay with this?

**Comment by TravisCarden** [comment]
Absolutely, @danepowell. Go ahead and make a release. Thanks!

**Comment by danepowell** [comment]
https://github.com/acquia/coding-standards-php/releases/tag/v0.5.0
