### ISSUE TITLE
AcquiaPHP standard should enforce indent length

### ISSUE THREAD

**Issue by balsama** [acquia/coding-standards-php#16]
I begrudgingly suggest two spaces to be aligned with Drupal.

**Comment by balsama** [comment]
It seems we've standardized on using `AcquiaDrupalStrict`, so this is less important.

**Comment by balsama** [comment]
Ok, so we have at least one project, Acquia CLI that uses the AcquiaPHP standard. So this is now _more_ important again 😅.

**Comment by danepowell** [comment]
I'm onboard with this as someone who agrees we should be more like Drupal, but I have a couple of concerns about the implementation and slippery slope that this puts us on:
- Drupal doesn't use a simple `PEAR.WhiteSpace.ScopeIndent` rule, it actually [defines its own sniff](https://git.drupalcode.org/project/coder/-/blob/8.3.x/coder_sniffer/Drupal/Sniffs/WhiteSpace/ScopeIndentSniff.php). Being consistent with Drupal would mean introducing a dependency on Drupal in AcquiaPHP.
- More generally, if the goal is to be "more like Drupal", it seems like individual projects should switch to a Drupal standard. The point of having a separate AcquiaPHP standard is that it's not coupled to Drupal. Having said that, of course it is _our_ standard so we can define it however we want, including to have 2 spaces, regardless of similarities to Drupal! 😄 
- There are ways that many projects (see below) break from Drupal standards that are at least as "bad" in my opinion as using 4 spaces, such as putting opening braces on new lines.

For reference, here are existing projects I found at Acquia using the AcquiaPHP standard:
- https://github.com/acquia/automatic-updater
- https://github.com/acquia/cli
- https://github.com/acquia/cloud-ide-hibernation (uses 4 spaces currently)
- https://github.com/acquia/blt-launcher

@TravisCarden any opinions?

**Comment by TravisCarden** [comment]
Let's go ahead and do it, @danepowell. `AcquiaPHP` is nothing but a collection of sniffs from other rulesets to begin with, and the "dependency" on `Drupal` would be light. I've submitted #17 for your review.
