### ISSUE TITLE
Function naming convention

### ISSUE THREAD

**Issue by vbouchet31** [acquia/coding-standards-php#39]
The [Drupal coding standards are saying](https://www.drupal.org/docs/develop/standards/coding-standards#s-functions-and-variables): "Functions should in addition have the grouping/module name as a prefix, to avoid name collisions between modules."

However, when executing `blt validate:phpcs` with the default phpcs.xml.dist (containing `<rule ref="AcquiaDrupalStrict"/>`) the following code is accepted:
mymodule.module
```
function super_function($variable) {
```
I would expect the validation to fail. The naming should be mymodule_super_function() or _mymodule_super_function().

**Comment by vbouchet31** [comment]
I realised this repo is only a list of ruleset. I create an issue in coder issue queue: https://www.drupal.org/project/coder/issues/3271952

**Comment by TravisCarden** [comment]
Thanks, @vbouchet31. Let's close this issue for now since there's nothing immediately actionable on it. Please report back when the upstream issue is fixed and released.
