### ISSUE TITLE
I should be able to use $_ENV

### ISSUE THREAD

**Issue by mglaman** [acquia/coding-standards-php#49]
The latest release prevents using globals. vlucas/phpdotenv encourages using `$_ENV` because it is thread safe. See https://github.com/vlucas/phpdotenv#putenv-and-getenv

**Comment by danepowell** [comment]
Putting aside thread safety for a moment, there are other reasons why superglobals including $_ENV are bad when distributing libraries and modules. Previous discussion on this:

- https://github.com/acquia/coding-standards-php/issues/9
- https://github.com/acquia/blt/issues/4005
- https://github.com/slevomat/coding-standard/issues/911

tl;dr: PHP has a config setting `variables_order` that varies between environments, affects how `$_ENV` can be accessed, and has a history of generating support tickets. The only way to prevent that as a package maintainer is to disallow usage of `$_ENV`.

To the point of thread safety, this wasn't something I was aware of and I agree it's concerning. But vlucas himself comments in the issue discussing thread safety that if this is an issue in production, [you're holding it wrong](https://github.com/vlucas/phpdotenv/issues/76#issuecomment-87252126). At least that's my interpretation.

In the end, I guess we're balancing a known problem (support tickets generated by inconsistent variables_order and $_ENV usage) against a theoretical one (thread safety).

**Comment by danepowell** [comment]
Thanks for the Drush reference, I vaguely recall that being a problem.

I'm a little wigged out by the thread safety issue. But until somewhat demonstrates that actually causing problems, I don't see much choice but to let it go.

**Comment by danepowell** [comment]
I referenced this thread in the AcquiaPHP ruleset so we can avoid sharding or repeating this discussion: https://github.com/acquia/coding-standards-php/commit/08dd037ac967ae5e2bb2951fadab9b3d361757be

**Comment by danepowell** [comment]
Another reason to use putenv, it _actually_ modifies the process environment, unlike `$_ENV` which despite its name is just one more global variable. And global variables are bad.
